---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.2
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(ggplot2)
library(reshape2)
```

```{r}
plotfun = function(x, idlabel, plotlabel, addlegend)
    {
    x = cbind(x,DM=1)
    x = x[,c(1,6,2,3,4,5)]
    df=melt(data.frame(x),id.var=idlabel)
    theplot = ggplot(df, aes_string(x=idlabel, y="value", col="variable")) 
    theplot = theplot + geom_line(lwd=2)
    theplot = theplot + ylim(0, 1.2)
    theplot = theplot + theme_bw()
    theplot = theplot + theme(legend.background = element_rect(size=0.5, linetype="solid", colour ="black"))
    theplot = theplot + labs(y = "Relative Variance", x = plotlabel)
    theplot = theplot + theme(axis.text.x = element_text(colour="grey20",size=16))
    theplot = theplot + theme(axis.text.y = element_text(colour="grey20",size=16))
    theplot = theplot + theme(axis.title.x = element_text(colour="grey20",size=16))
    theplot = theplot + theme(axis.title.y = element_text(colour="grey20",size=16))
    theplot = theplot + theme(legend.title=element_blank())
#    theplot = theplot + scale_color_manual(labels = "LOOP", "ReLOOP","ReLOOP+RF", "ReLOOP+EN"), values = c("lightblue", "orange", "violet", "black"))
    theplot = theplot + scale_color_manual(labels = c("DM", expression(list(bold(x),"RF")), expression(list(x^r,"LS")), expression(list(tilde(bold(x)),"RF")), expression(list(tilde(bold(x)),"EN"))), values = c("gray", "lightblue", "orange", "violet", "black"))
    theplot = theplot + theme(legend.position = c(0.1, 0.15))
    theplot = theplot + theme(legend.text = element_text(size=18))
    if (!addlegend) theplot = theplot + theme(legend.position = "none")
    return(theplot)
}

plotwrapper=function(plots, filename, idlabel, plotlabel)
    {
    pdf(filename)
    for (i in 1:4) print(plotfun(plots[[i]], idlabel, plotlabel, i==3))
    dev.off()    
}
```

```{r}
load("results/r2c_res.RData")
idlabel="r2c"
    xn = length(res)/4
    plots = matrix(NA,xn,5)
    colnames(plots)=c(idlabel, "LOOP", "ReLOOP+RF", "ReLOOP+EN", "ReLOOP")
    plots=rep(list(plots),4)
    for (i in 1:4)
        {
        for (j in 1:xn)
            {
            entry = res[[(i-1)*xn+j]]
            plots[[i]][j,1] = entry[[idlabel]]
            plots[[i]][j,2:5] = (entry$results[2:5,2]/entry$results[1,2])^2
        }
        plots[[i]] = plots[[i]][,c(1,2,5,3,4)]
    }

plotwrapper(plots, "plots/r2c.pdf", "r2c", "Covariates: R-squared")
```

```{r}
load("results/r2p_res.RData")
idlabel="r2p"
    plots = matrix(NA,10,5)
    colnames(plots)=c(idlabel, "LOOP", "ReLOOP+RF", "ReLOOP+EN", "ReLOOP")
    plots=rep(list(plots),4)
    is = c(1,2,21,22)
    js = 2*(0:9)
    for (i in 1:4)
        {
        for (j in 1:10)
            {
            entry = res[[is[i]+js[j]]]
            plots[[i]][j,1] = entry[[idlabel]]
            plots[[i]][j,2:5] = (entry$results[2:5,2]/entry$results[1,2])^2
        }
        plots[[i]] = plots[[i]][,c(1,2,5,3,4)]
    }
plotwrapper(plots, "plots/r2p.pdf", "r2p", "Remnant Predictions: R-squared")
```

```{r}
load("results/sampsize_res.RData")
idlabel="N"
    plots = matrix(NA,8,5)
    colnames(plots)=c(idlabel, "LOOP", "ReLOOP+RF", "ReLOOP+EN", "ReLOOP")
    plots=rep(list(plots),4)
    is = c(1,3,2,4)
    js = 4*(0:7)
    for (i in 1:4)
        {
        for (j in 1:8)
            {
            entry = res[[is[i]+js[j]]]
            plots[[i]][j,1] = entry[[idlabel]]
            plots[[i]][j,2:5] = (entry$results[2:5,2]/entry$results[1,2])^2
        }
        plots[[i]] = plots[[i]][,c(1,2,5,3,4)]
    }
plotwrapper(plots, "plots/sampsize.pdf", "N", "Sample Size")
```

